state: US

links:
- name: variant_proportions
  url: https://covid.cdc.gov/covid-data-tracker/#variant-proportions
  renderSettings:
    clipRectangle:
      top: 0
      height: 5500
      width: 1400

- name: published_sequences
  url: https://covid.cdc.gov/covid-data-tracker/#published-covid-sequences
  renderSettings:
    clipRectangle:
      top: 0
      height: 4400
      width: 1400

- name: global_map
  url: https://covid.cdc.gov/covid-data-tracker/#global-variant-report-map
  renderSettings:
    clipRectangle:
      top: 0
      height: 3000
      width: 1400
