state: WA

links:
- name: primary
  url: https://doh.wa.gov/sites/default/files/2022-02/SARS-CoV-2%20Sequencing%20Data.xlsx
  file: xlsx
  message: downloading Excel for WA primary

- name: variants_report
  url: https://www.doh.wa.gov/Portals/1/Documents/1600/coronavirus/data-tables/420-316-SequencingAndVariantsReport.pdf
  file: pdf
