state: AK

links:
- name: primary
  url: https://dhss.alaska.gov/dph/Epi/id/Pages/COVID-19/covidandflu.aspx

- name: secondary
  url: https://dhss.alaska.gov/dph/epi/id/siteassets/pages/HumanCoV/COVID_monthly_update.pdf
  file: pdf
