state: GA

links:
- name: primary
  eval: True
  url: (date.today() - timedelta(days=date.today().weekday() - 2)).strftime("https://breakthroughreports.s3.amazonaws.com/Breakthrough+Report_%y%m%d.html")
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(10000);
    page.done();
  renderSettings:
    clipRectangle:
      height: 1400
      width: 1400

- name: summary
  eval: True
  url: (date.today() - timedelta(days=date.today().weekday() - 2)).strftime("https://breakthroughreports.s3.amazonaws.com/Breakthrough+Report_%y%m%d.html#summary")
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(10000);
    page.done();
  renderSettings:
    clipRectangle:
      height: 1400
      width: 1400

- name: demographics
  eval: True
  url: (date.today() - timedelta(days=date.today().weekday() - 2)).strftime("https://breakthroughreports.s3.amazonaws.com/Breakthrough+Report_%y%m%d.html#demographics")
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(10000);
    page.done();
  renderSettings:
    clipRectangle:
      height: 1400
      width: 1400

- name: days-to-breakthrough
  eval: True
  url: (date.today() - timedelta(days=date.today().weekday() - 2)).strftime("https://breakthroughreports.s3.amazonaws.com/Breakthrough+Report_%y%m%d.html#days-to-breakthrough")
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(10000);
    page.done();
  renderSettings:
    clipRectangle:
      height: 1400
      width: 1400

- name: counts
  eval: True
  url: (date.today() - timedelta(days=date.today().weekday() - 2)).strftime("https://breakthroughreports.s3.amazonaws.com/Breakthrough+Report_%y%m%d.html#counts")
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(10000);
    page.done();
  renderSettings:
    clipRectangle:
      height: 1400
      width: 1400

- name: rates
  eval: True
  url: (date.today() - timedelta(days=date.today().weekday() - 2)).strftime("https://breakthroughreports.s3.amazonaws.com/Breakthrough+Report_%y%m%d.html#rates")
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(10000);
    page.done();
  renderSettings:
    clipRectangle:
      height: 1400
      width: 1400
