state: NJ

links:
- name: primary
  url: https://dashboards.doh.nj.gov/views/DailyConfirmedCaseSummary7_22_2020/CasesByVaccinationStatus
  renderSettings:
    viewport:
      height: 1600
      width: 1552 
