state: US

links:
- name: breakthrough_cases
  url: https://www.cdc.gov/vaccines/covid-19/health-departments/breakthrough-cases.html

- name: cases_by_vax_status
  url: https://covid.cdc.gov/covid-data-tracker/#rates-by-vaccine-status
  renderSettings:
    clipRectangle:
      top: 0
      height: 4400
      width: 1400
  
- name: cases_or_deaths_by_age_and_vax_status
  url: https://data.cdc.gov/api/views/3rge-nu2a/rows.csv?accessType=DOWNLOAD
  file: csv

- name: cases_or_deaths_by_age_and_vax_status_booster
  url: https://data.cdc.gov/api/views/d6p8-wqjm/rows.csv?accessType=DOWNLOAD
  file: csv

- name: cases_or_deaths_by_age_and_vax_status_second_booster
  url: https://data.cdc.gov/api/views/ukww-au2k/rows.csv?accessType=DOWNLOAD
  file: csv

