state: WA

links:
- name: primary
  url: https://www.doh.wa.gov/Portals/1/Documents/1600/coronavirus/data-tables/421-010-CasesInNotFullyVaccinated.pdf
  file: pdf

- name: breakthrough_report
  url: https://www.doh.wa.gov/Portals/1/Documents/1600/coronavirus/data-tables/420-339-VaccineBreakthroughReport.pdf
  file: pdf
